document.writeln("<header>");
document.writeln("			<h3>同烁输血--护理端</h3>");
document.writeln("			<div id=\'nav\'>");
document.writeln("				<ul>");
document.writeln("					<li class=\'active\'><a href=\'transfusion.html\'>输血单申请</a></li>");
document.writeln("					<li><a href=\'teg.html'>TEG申请单</a></li>");
document.writeln("					<li><a href=\'other.html\'>其他检验申请</a></li>");
document.writeln("					<li><a href=\'bcollection.html\'>血采集管理</a></li>");
document.writeln("					<li><a href=\'specimen.html\'>标本送出</a></li>");
document.writeln("					<li><a href=\'breceive.html\'>领血管理</a></li>");
document.writeln("					<li><a href=\'bprocess.html\'>输血流程</a></li>");
document.writeln("					<li><a href=\'brecord.html\'>输血记录</a></li>");
document.writeln("				</ul>");
document.writeln("				<div id=\'line\'>");
document.writeln("					");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'#\'>打印机设定</a></li>");
document.writeln("				<li><a href=\'#\'>修改密码</a></li>");
document.writeln("				<li><a href=\'#\'>系统帮助</a></li>");
document.writeln("				<li><a href=\'#\'>联系我们</a></li>");
document.writeln("				<li><a href=\'#\'>退出登录</a></li>");
document.writeln("			</ul>");
document.writeln("		</header>");
document.writeln("		<div id=\'hhead\'>");
document.writeln("		</div>");