document.writeln("		<div class=\'header\'>");
document.writeln("			<h3>同烁输血--实验室端</h3>");
document.writeln("			<div id=\'nav\'>");
document.writeln("<ul>");
document.writeln("				<li>");
document.writeln("					<a href=\'index.html\'>首页</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>申请单管理</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'btransfusion.html\'>输血申请</a></li>");
document.writeln("						<li><a href=\'bstoring.html\'>自储血申请</a></li>");
document.writeln("						<li><a href=\'teg.html\'>TEG申请</a></li>");
document.writeln("						<li><a href=\'bsingle.html\'>单采治疗申请</a></li>");
document.writeln("						<li><a href=\'bothers.html\'>其他检验申请</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>血库管理</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'bin.html\'>入库管理</a></li>");
document.writeln("						<li><a href=\'bout.html\'>出库管理</a></li>");
document.writeln("						<li><a href=\'bdiscarde.html\'>报废管理</a></li>");
document.writeln("						<li><a href=\'bcancel.html\'>退血管理</a></li>");
document.writeln("						<li><a href=\'brepertory.html\'>库存管理</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>实验室管理</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'bmanagement.html\'>标本管理</a></li>");
document.writeln("						<li><a href=\'bcheck.html\'>标本检测</a></li>");
document.writeln("						<li><a href=\'bcrossmatching.html\'>交叉配血</a></li>");
document.writeln("						<li><a href=\'laboratory.html\'>预出库管理</a></li>");
document.writeln("						<li><a href=\'btest.html\'>其他检验管理</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>血袋管理</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'bbagmelting.html\'>血袋融化</a></li>");
document.writeln("						<li><a href=\'bbagrecovery.html\'>血袋回收</a></li>");
document.writeln("						<li><a href=\'#\'>血袋销毁</a></li>");
document.writeln("						<li><a href=\'#\'>xxxx</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>查询管理</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'bsample.html\'>标本查询</a></li>");
document.writeln("						<li><a href=\'bpatient.html\'>患者查询</a></li>");
document.writeln("						<li><a href=\'bloodbag.html\'>血袋查询</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>报表管理</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'bprocess.html\'>xxx</a></li>");
document.writeln("						<li><a href=\'#\'>xxx</a></li>");
document.writeln("						<li><a href=\'#\'>xxx</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>其它管理</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'#\'>报告管理</a></li>");
document.writeln("						<li><a href=\'dwarehousing.html\'>药品入库</a></li>");
document.writeln("						<li><a href=\'dinventory.html\'>药品库存</a></li>");
document.writeln("						<li><a href=\'bautologous.html\'>自体血采集</a></li>");
document.writeln("						<li><a href=\'bautologouscollect.html\'>自体血管理</a></li>");
document.writeln("						<li><a href=\'bagreement.html\'>同意书管理</a></li>");
document.writeln("						<li><a href=\'other.html\'>互助献血管理</a></li>");
document.writeln("						<li><a href=\'bcard.html\'>献血证管理</a></li>");
document.writeln("						<li><a href=\'btemperature.html\'>温控管理</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("				<div id=\'line\'>");
document.writeln("					");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'#\'>打印机设定</a></li>");
document.writeln("				<li><a href=\'#\'>修改密码</a></li>");
document.writeln("				<li><a href=\'#\'>系统帮助</a></li>");
document.writeln("				<li><a href=\'#\'>联系我们</a></li>");
document.writeln("				<li><a href=\'#\'>退出登录</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("		<div id=\'hhead\'>");
document.writeln("		</div>");